name: Firebase Deployment
on:
  push:
    branches:
      -main

jobs:
    deploy:
      name: Build & Deployment
      runs-on: ubuntu-latest

      steps:
        - name: get
          uses: actions/checkout@v3

        - name: install node
          uses: actions/setup-node@v3
          with:
              node-version: "18x"
              
        - name: install node packages
          run: npm i

        - name: Build
          run : npm run build
          env:
            CI: false

        - name: Deploy to Firebase Hosting
          uses: w9jds/firebase-action@v12.4.0
          with:
              args: deploy --only hosting
          env: 
              FIREBASE_TOKEN: $({secrets.FIREBASE_TOKEN})