name : Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deployment
    runs-on : ubuntu-latest

    steps:
      - name : get the source code
        uses: actions/checkout@v3

      - name : install node
        uses: actions/setup-node@v3
        with:
            node-version: '18'

      - name : install node packages
        run: npm i

      - name: Build
        run: npm run build
        env:
          CI: false
      
      - name : Deploy to Vercel
        uses: w9jds/firebase-action@master
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
